CSCD70: dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange > Class Template Reference
dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange > Class Template Reference abstract
#include "Assignment2-Dataflow_Analysis/include/DFA/Flow/Framework.h"
Protected Types
using DomainIdMap_t = typename TDomainElem::DomainIdMap_t
using DomainVector_t = typename TDomainElem::DomainVector_t
using DomainVal_t = typename TMeetOp::DomainVal_t
using MeetOperands_t = std::vector< DomainVal_t >
using MeetBBConstRange_t = TMeetBBConstRange
using BBConstRange_t = TBBConstRange
using InstConstRange_t = TInstConstRange
using AnalysisResult_t = std::tuple< DomainIdMap_t, DomainVector_t, std::unordered_map< const llvm::BasicBlock *, DomainVal_t >, std::unordered_map< const llvm::Instruction *, DomainVal_t > >
Protected Member Functions
virtual ~Framework ()
virtual bool transferFunc (const llvm::Instruction &Inst, const DomainVal_t &IDV, DomainVal_t &ODV)=0
Apply the transfer function to the input domain value at instruction inst .
virtual AnalysisResult_t run (llvm::Function &F, llvm::FunctionAnalysisManager &FAM)
Print utility functions
std::string stringifyDomainWithMask (const DomainVal_t &Mask) const
virtual void printInstDomainValMap (const llvm::Instruction &Inst) const =0
void printInstDomainValMap (const llvm::Function &F) const
virtual std::string getName () const =0
Boundary values
DomainVal_t getBoundaryVal (const llvm::BasicBlock &BB) const
virtual MeetBBConstRange_t getMeetBBConstRange (const llvm::BasicBlock &BB) const =0
Get the list of basic blocks to which the meet operator will be applied.
virtual MeetOperands_t getMeetOperands (const llvm::BasicBlock &BB) const
Get the list of domain values to which the meet operator will be applied.
DomainVal_t bc () const
DomainVal_t meet (const MeetOperands_t &MeetOperands) const
CFG traversal
virtual BBConstRange_t getBBConstRange (const llvm::Function &F) const =0
Get the list of basic blocks from the function.
virtual InstConstRange_t getInstConstRange (const llvm::BasicBlock &BB) const =0
Get the list of instructions from the basic block.
bool traverseCFG (const llvm::Function &F)
Traverse through the CFG of the function.
Protected Attributes
DomainIdMap_t DomainIdMap
DomainVector_t DomainVector
std::unordered_map< const llvm::BasicBlock *, DomainVal_t > BVs
std::unordered_map< const llvm::Instruction *, DomainVal_t > InstDomainValMap
Detailed Description
template<typename TDomainElem, typename TValue, typename TMeetOp, typename TMeetBBConstRange, typename TBBConstRange, typename TInstConstRange>
class dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >
Definition at line 18 of file Framework.h.
Member Typedef Documentation
AnalysisResult_t
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > using dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::AnalysisResult_t = std::tuple<DomainIdMap_t, DomainVector_t, std::unordered_map<const llvm::BasicBlock *, DomainVal_t>, std::unordered_map<const llvm::Instruction *, DomainVal_t> > protected
Definition at line 27 of file Framework.h.
BBConstRange_t
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > using dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::BBConstRange_t = TBBConstRange protected
Definition at line 25 of file Framework.h.
DomainIdMap_t
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > using dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainIdMap_t = typename TDomainElem::DomainIdMap_t protected
Definition at line 20 of file Framework.h.
DomainVal_t
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > using dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainVal_t = typename TMeetOp::DomainVal_t protected
Definition at line 22 of file Framework.h.
DomainVector_t
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > using dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainVector_t = typename TDomainElem::DomainVector_t protected
Definition at line 21 of file Framework.h.
InstConstRange_t
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > using dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::InstConstRange_t = TInstConstRange protected
Definition at line 26 of file Framework.h.
MeetBBConstRange_t
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > using dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::MeetBBConstRange_t = TMeetBBConstRange protected
Definition at line 24 of file Framework.h.
MeetOperands_t
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > using dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::MeetOperands_t = std::vector<DomainVal_t> protected
Definition at line 23 of file Framework.h.
Constructor & Destructor Documentation
~Framework()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > virtual dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::~Framework () inline protected virtual
Definition at line 132 of file Framework.h.
Member Function Documentation
bc()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > DomainVal_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::bc () const inline protected
Definition at line 96 of file Framework.h.
References dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainIdMap.
getBBConstRange()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > virtual BBConstRange_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::getBBConstRange (const llvm::Function & F) const protected pure virtual
Get the list of basic blocks from the function.
Parameters
F
Returns
Implemented in dfa::ForwardAnalysis< TDomainElem, TValue, TMeetOp >, and dfa::ForwardAnalysis< dfa::Expression, dfa::Bool, dfa::Intersect< dfa::Bool > >.
getBoundaryVal()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > DomainVal_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::getBoundaryVal (const llvm::BasicBlock & BB) const inline protected
Todo:
(CSCD70) Please complete this method.
Definition at line 71 of file Framework.h.
References dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::getMeetOperands(), and dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::meet().
getInstConstRange()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > virtual InstConstRange_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::getInstConstRange (const llvm::BasicBlock & BB) const protected pure virtual
Get the list of instructions from the basic block.
Parameters
BB
Returns
Implemented in dfa::ForwardAnalysis< TDomainElem, TValue, TMeetOp >, and dfa::ForwardAnalysis< dfa::Expression, dfa::Bool, dfa::Intersect< dfa::Bool > >.
getMeetBBConstRange()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > virtual MeetBBConstRange_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::getMeetBBConstRange (const llvm::BasicBlock & BB) const protected pure virtual
Get the list of basic blocks to which the meet operator will be applied.
Parameters
BB
Returns
Implemented in dfa::ForwardAnalysis< TDomainElem, TValue, TMeetOp >, and dfa::ForwardAnalysis< dfa::Expression, dfa::Bool, dfa::Intersect< dfa::Bool > >.
getMeetOperands()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > virtual MeetOperands_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::getMeetOperands (const llvm::BasicBlock & BB) const inline protected virtual
Get the list of domain values to which the meet operator will be applied.
Parameters
BB
Returns
See also
getMeetBBConstRange
Todo:
(CSCD70) Please complete this method.
Definition at line 89 of file Framework.h.
Referenced by dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::getBoundaryVal().
getName()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > virtual std::string dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::getName () const protected pure virtual
meet()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > DomainVal_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::meet (const MeetOperands_t & MeetOperands) const inline protected
Todo:
(CSCD70) Please complete this method.
Definition at line 97 of file Framework.h.
References dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainIdMap.
Referenced by dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::getBoundaryVal().
printInstDomainValMap() [1/2]
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > void dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::printInstDomainValMap (const llvm::Function & F) const inline protected
Definition at line 60 of file Framework.h.
References dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::printInstDomainValMap().
printInstDomainValMap() [2/2]
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > virtual void dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::printInstDomainValMap (const llvm::Instruction & Inst) const protected pure virtual
Implemented in dfa::ForwardAnalysis< TDomainElem, TValue, TMeetOp >, and dfa::ForwardAnalysis< dfa::Expression, dfa::Bool, dfa::Intersect< dfa::Bool > >.
Referenced by dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::printInstDomainValMap().
run()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > virtual AnalysisResult_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::run (llvm::Function & F, llvm::FunctionAnalysisManager & FAM) inline protected virtual
Todo:
(CSCD70) Please complete this method.
Definition at line 143 of file Framework.h.
References dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::BVs, dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainIdMap, dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainVector, and dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::InstDomainValMap.
stringifyDomainWithMask()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > std::string dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::stringifyDomainWithMask (const DomainVal_t & Mask) const inline protected
Definition at line 40 of file Framework.h.
References CHECK, dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainIdMap, dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainVector, and dfa::ValuePrinter< TValue >::print().
transferFunc()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > virtual bool dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::transferFunc (const llvm::Instruction & Inst, const DomainVal_t & IDV, DomainVal_t & ODV) protected pure virtual
Apply the transfer function to the input domain value at instruction inst .
Parameters
Inst
IDV
ODV
Returns
Whether the output domain value is to be changed.
traverseCFG()
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > bool dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::traverseCFG (const llvm::Function & F) inline protected
Traverse through the CFG of the function.
Parameters
F
Returns
True if either BasicBlock-DomainValue mapping or Instruction-DomainValue mapping has been modified, false otherwise.
Todo:
(CSCD70) Please complete this method.
Definition at line 122 of file Framework.h.
Member Data Documentation
BVs
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > std::unordered_map<const llvm::BasicBlock *, DomainVal_t> dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::BVs protected
Definition at line 34 of file Framework.h.
Referenced by dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::run().
DomainIdMap
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > DomainIdMap_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainIdMap protected
Definition at line 32 of file Framework.h.
Referenced by dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::bc(), dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::meet(), dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::run(), and dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::stringifyDomainWithMask().
DomainVector
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > DomainVector_t dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::DomainVector protected
Definition at line 33 of file Framework.h.
Referenced by dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::run(), and dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::stringifyDomainWithMask().
InstDomainValMap
template<typename TDomainElem , typename TValue , typename TMeetOp , typename TMeetBBConstRange , typename TBBConstRange , typename TInstConstRange > std::unordered_map<const llvm::Instruction *, DomainVal_t> dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::InstDomainValMap protected
Definition at line 35 of file Framework.h.
Referenced by dfa::Framework< TDomainElem, TValue, TMeetOp, TMeetBBConstRange, TBBConstRange, TInstConstRange >::run().
The documentation for this class was generated from the following file:
Assignment2-Dataflow_Analysis/include/DFA/Flow/Framework.h